### ISSUE TITLE
Saved filename contains folder name

### ISSUE THREAD

**Issue by RomRoc** [lzx1413/LabelImgTool#8]
Hello, thanks for your great annotation tool. There is a small bug in my version, I run it in Ubuntu, I use it in SEG mode.
If I choose a directory as default annotation dir from menu File, when I save the annotations it saves the files in containing dir, with a filename that is folder+annotation_file_name.
I.e.: default annotation dir = /home/me/annotation, file name = myimage.jpg, it saves annotations files = /home/me/annotationmyimage.json, instead of /home/me/annotation/myimage.json
I think you should just add a / to file name.
Thanks

**Comment by lzx1413** [comment]
Thanks for your comments, I will fix that soon
