### ISSUE TITLE
segmentation mode revert one step

### ISSUE THREAD

**Issue by WillSuen** [lzx1413/LabelImgTool#9]
For segmentation mode creating polygon, if I made a mistake and want to revert one step, is there a possible way? I don't want to discard all polygon steps and start over. Thanks.

**Comment by lzx1413** [comment]
All of the points are appended to a list, you can delete every single point as you wish. The reference code is at https://github.com/lzx1413/LabelImgTool/blob/master/libs/shape.py and https://github.com/lzx1413/LabelImgTool/blob/master/libs/canvas.py
